package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u191/11894/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Saturday, October 6, 2018 5:43:21 AM PDT
*/

public interface UNKNOWN
{

  /**
     * XXX
     */
  public static final short value = (short)(5);
}
